### ISSUE TITLE
can't decompile rpyc files

### ISSUE THREAD

**Issue by fisch123456** [CensoredUsername/unrpyc#107]
![rpyc](https://user-images.githubusercontent.com/69847532/104125594-1e915300-5358-11eb-9b0e-fc97b4940a37.PNG)
Hi I would like to ask you how can I decompile rpyc files.I tried everything that is stated in your readme list.-get rpyc in the same directory.But it still failed.Is there necessarz to compile all program in visual studio or python or have in directory clear renpy?I downloanded this a year before and it worked but I forgot how to do it again.Even when I have rpyc it shows me error when I want to play.
![eror](https://user-images.githubusercontent.com/69847532/104125781-4e8d2600-5359-11eb-8b62-4517de187cf5.PNG)

The game is doki doki. Please help me. Thanks for reply.

**Comment by CensoredUsername** [comment]
I'm not sure what went wrong there but it doesn't seem like an issue from the unrpyc side. The game itself is giving an error, it can't find the file "lecturehall.jpg", which is probably stored in one of the archives of the game. That's weird, because un.rpyc doesn't actually mess with that at all.

Try doing a clean reinstall of the game. Then validate that it works without un.rpyc present. Then try again with un.rpyc present once.

**Comment by fisch123456** [comment]
I did it, thank you
