### ISSUE TITLE
traceback: un.rpyc cannot be found, even though its there.

### ISSUE THREAD

**Issue by a-rabin** [CensoredUsername/unrpyc#128]
Hello.
I tried to decompile a game where the `archive.rpa` was most likely obfuscated. I copied `bytecode.rpyb` and `un.rpyc` on the correct folders, but when I run the game it crashes, and the traceback returns.
how to fix?

**Comment by CensoredUsername** [comment]
Could you post the traceback?

**Comment by a-rabin** [comment]
`I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file G:\Games\SymphonicLove-v0.15-pc/game/un.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 447, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "renpy/script.py", line 283, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "renpy/script.py", line 789, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file G:\Games\SymphonicLove-v0.15-pc/game/un.rpyc.

Windows-8.1-6.3.9600
Ren'Py 7.4.7.1862
Symphonic Love v0.15
Fri Aug 20 16:13:43 2021
`

**Comment by CensoredUsername** [comment]
Probably the game disabled legacy un.rpyc support, so it can't load un.rpyc.

Does bytecode.rpyb on its own work?

**Comment by a-rabin** [comment]
i mean the game runs with bytecode, but nothing is extracted, i think.

**Comment by CensoredUsername** [comment]
Did you copy in a new bytecode.rpyb file? the game normally overwrites it afterwards.
Otherwise I'm going to need a bit more details.

**Comment by a-rabin** [comment]
yes, i do copy a new `bytecode.rpyb` file (20KB) everytime.

**Comment by CensoredUsername** [comment]
I investigated a bit. The reason un.rpyc seems to fail on this game is simply because the game ships with the complete set of uncompiled files in its archive, and un.rpyc tries to avoid overwriting .rpy files if they're already present. Unfortunately the API used for that doesn't detect if a file is present in an archive or on the filesystem.

So you don't need unrpyc for this at all, you just need to extract the files from the archive. The author did a slight funny there and altered the file signature of the archive so the normal tools think it's not a valid archive. Simply change the first eight bytes of the archive from `ZiX-12A ` to `RPA-3.2 ` and you can just extract the original files with something like rpatool or unrpa.

**Comment by a-rabin** [comment]
okay, i do know what to do, but how can i change them without notepad++ going haywire? (because the archive is about 900MB)

**Comment by CensoredUsername** [comment]
Use a hex editor like [HxD](https://mh-nexus.de/en/hxd/). They're built for that kind of stuff.

**Comment by a-rabin** [comment]
changed the bytes, but still showing error "not a valid archive" in `rpaExtract.exe`

**Comment by CensoredUsername** [comment]
huh, weird. It worked for me. Either way, this isn't a problem with unrpyc so I can't help you much further.
